[package]
name = "LayerN_Circuits"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
log = "0.4.20"
plonky2 = "0.1.4"
plonky2_field = "0.1.1"
serde_json = "1.0.108"

[workspace.dependencies]
ahash = "0.8.7"

[workspace.metadata.resolver]
version = "2"
